name: Validate
on:
  pull_request:
    branches:
      - master
jobs:
  validate:
    name: Validate typescript
    uses: bratislava/github-actions/.github/workflows/validate-typescript.yml@stable
  # if you need different setting uncomment lines bellow
  #    with:
  #      node: 20
  #      workdir: './next'
  #      level: warning
